apiVersion: v1
kind: ReplicationController
metadata:
  name: petservice 
  labels:
    name: petservice 
spec:
  replicas: 1
  selector:
    name: petservice 
  template:
    metadata:
      labels:
        name: petservice 
    spec:
      containers:
      - name: petservice 
        image: sameera/petstore:1.0 
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          #           # instead access environment variables to find service host
          #                     # info, comment out the 'value: dns' line above, and uncomment the
          #                               # line below.
          #                                         # value: env
        ports:
        - containerPort: 8082
